# Week 11 - Numpy breakout

Working through this will help you think through your homework. Using NumPy:
1. Create a dataset of 50 random integers ranging from 0 and 100.
2. Reshape the data to be 10x5.
3. Create a dataset of 50 numbers between 0 and 100 using linspace()
4. Reshape the data to be 10x5.
5. Use vstack to stack the data for the two arrays call it "vertstk"
6. Use hstack to stack the data for the two arrays call it "hozstk"
7. for each array divide each element by 2:<br>
    a. Use a functional tools (such as map or filter) for hozstk then a vectorized approach for vertstk<br>
    b. for an extra challenge replace all values greater than 25 with 25
8. get column and row means for hozstk and vertstk

In [2]:
import numpy as np
print (np.__version__)

1.13.1


In [3]:
np.random.seed(100)

In [4]:
#1. Create a dataset of 50 random integers ranging from 0 and 100.

a = np.random.randint(0,100,50)
a

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98, 53, 66, 98, 14, 34, 24, 15,
       60, 58, 16,  9, 93, 86,  2, 27,  4, 31,  1, 13, 83,  4, 91, 59, 67,
        7, 49, 47, 65, 61, 14, 55, 71, 80,  2, 94, 19, 98, 63, 53, 27])

In [5]:
#2. Reshape the data to be 10x5.

a.reshape(10,5)

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98],
       [53, 66, 98, 14, 34],
       [24, 15, 60, 58, 16],
       [ 9, 93, 86,  2, 27],
       [ 4, 31,  1, 13, 83],
       [ 4, 91, 59, 67,  7],
       [49, 47, 65, 61, 14],
       [55, 71, 80,  2, 94],
       [19, 98, 63, 53, 27]])

In [6]:
a

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98, 53, 66, 98, 14, 34, 24, 15,
       60, 58, 16,  9, 93, 86,  2, 27,  4, 31,  1, 13, 83,  4, 91, 59, 67,
        7, 49, 47, 65, 61, 14, 55, 71, 80,  2, 94, 19, 98, 63, 53, 27])

In [7]:
a = a.reshape(10,5)
a

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98],
       [53, 66, 98, 14, 34],
       [24, 15, 60, 58, 16],
       [ 9, 93, 86,  2, 27],
       [ 4, 31,  1, 13, 83],
       [ 4, 91, 59, 67,  7],
       [49, 47, 65, 61, 14],
       [55, 71, 80,  2, 94],
       [19, 98, 63, 53, 27]])

In [8]:
#3. Create a dataset of 50 numbers between 0 and 100 using linspace()

b = np.linspace(0,100,50)
b

array([   0.        ,    2.04081633,    4.08163265,    6.12244898,
          8.16326531,   10.20408163,   12.24489796,   14.28571429,
         16.32653061,   18.36734694,   20.40816327,   22.44897959,
         24.48979592,   26.53061224,   28.57142857,   30.6122449 ,
         32.65306122,   34.69387755,   36.73469388,   38.7755102 ,
         40.81632653,   42.85714286,   44.89795918,   46.93877551,
         48.97959184,   51.02040816,   53.06122449,   55.10204082,
         57.14285714,   59.18367347,   61.2244898 ,   63.26530612,
         65.30612245,   67.34693878,   69.3877551 ,   71.42857143,
         73.46938776,   75.51020408,   77.55102041,   79.59183673,
         81.63265306,   83.67346939,   85.71428571,   87.75510204,
         89.79591837,   91.83673469,   93.87755102,   95.91836735,
         97.95918367,  100.        ])

In [9]:
#4. Reshape the data to be 10x5.

b = b.reshape(10,5)
b

array([[   0.        ,    2.04081633,    4.08163265,    6.12244898,
           8.16326531],
       [  10.20408163,   12.24489796,   14.28571429,   16.32653061,
          18.36734694],
       [  20.40816327,   22.44897959,   24.48979592,   26.53061224,
          28.57142857],
       [  30.6122449 ,   32.65306122,   34.69387755,   36.73469388,
          38.7755102 ],
       [  40.81632653,   42.85714286,   44.89795918,   46.93877551,
          48.97959184],
       [  51.02040816,   53.06122449,   55.10204082,   57.14285714,
          59.18367347],
       [  61.2244898 ,   63.26530612,   65.30612245,   67.34693878,
          69.3877551 ],
       [  71.42857143,   73.46938776,   75.51020408,   77.55102041,
          79.59183673],
       [  81.63265306,   83.67346939,   85.71428571,   87.75510204,
          89.79591837],
       [  91.83673469,   93.87755102,   95.91836735,   97.95918367,  100.        ]])

In [10]:
#print(a)
#print(b)

print(a.shape)
print(b.shape)

print()
vertstk = np.vstack((a,b))
print(vertstk.shape)

hozstk = np.hstack((a,b))
print(hozstk.shape)

(10, 5)
(10, 5)

(20, 5)
(10, 10)


In [11]:
#5. Use vstack to stack the data for the two arrays call it "vertstk"

vertstk = np.vstack((a,b))
print(vertstk)
print(vertstk.shape)

[[   8.           24.           67.           87.           79.        ]
 [  48.           10.           94.           52.           98.        ]
 [  53.           66.           98.           14.           34.        ]
 [  24.           15.           60.           58.           16.        ]
 [   9.           93.           86.            2.           27.        ]
 [   4.           31.            1.           13.           83.        ]
 [   4.           91.           59.           67.            7.        ]
 [  49.           47.           65.           61.           14.        ]
 [  55.           71.           80.            2.           94.        ]
 [  19.           98.           63.           53.           27.        ]
 [   0.            2.04081633    4.08163265    6.12244898    8.16326531]
 [  10.20408163   12.24489796   14.28571429   16.32653061   18.36734694]
 [  20.40816327   22.44897959   24.48979592   26.53061224   28.57142857]
 [  30.6122449    32.65306122   34.69387755   36.73

In [12]:
#6. Use hstack to stack the data for the two arrays call it "hozstk"

hozstk = np.hstack((a,b))
print(hozstk)
print(hozstk.shape)

[[   8.           24.           67.           87.           79.            0.
     2.04081633    4.08163265    6.12244898    8.16326531]
 [  48.           10.           94.           52.           98.
    10.20408163   12.24489796   14.28571429   16.32653061   18.36734694]
 [  53.           66.           98.           14.           34.
    20.40816327   22.44897959   24.48979592   26.53061224   28.57142857]
 [  24.           15.           60.           58.           16.
    30.6122449    32.65306122   34.69387755   36.73469388   38.7755102 ]
 [   9.           93.           86.            2.           27.
    40.81632653   42.85714286   44.89795918   46.93877551   48.97959184]
 [   4.           31.            1.           13.           83.
    51.02040816   53.06122449   55.10204082   57.14285714   59.18367347]
 [   4.           91.           59.           67.            7.
    61.2244898    63.26530612   65.30612245   67.34693878   69.3877551 ]
 [  49.           47.           65.      

In [13]:
?np.hstack()

In [14]:
#7. for each array divide each element by 2:<br>
#    a. Use a functional tools (such as map or filter) for hozstk then a vectorized approach for vertstk
#    b. for an extra challenge replace all values greater than 25 with 25

## Functional: Map (Note, this is not best practice but can be done.)
print(list(map(lambda x: x/2, hozstk)))

[array([  4.        ,  12.        ,  33.5       ,  43.5       ,
        39.5       ,   0.        ,   1.02040816,   2.04081633,
         3.06122449,   4.08163265]), array([ 24.        ,   5.        ,  47.        ,  26.        ,
        49.        ,   5.10204082,   6.12244898,   7.14285714,
         8.16326531,   9.18367347]), array([ 26.5       ,  33.        ,  49.        ,   7.        ,
        17.        ,  10.20408163,  11.2244898 ,  12.24489796,
        13.26530612,  14.28571429]), array([ 12.        ,   7.5       ,  30.        ,  29.        ,
         8.        ,  15.30612245,  16.32653061,  17.34693878,
        18.36734694,  19.3877551 ]), array([  4.5       ,  46.5       ,  43.        ,   1.        ,
        13.5       ,  20.40816327,  21.42857143,  22.44897959,
        23.46938776,  24.48979592]), array([  2.        ,  15.5       ,   0.5       ,   6.5       ,
        41.5       ,  25.51020408,  26.53061224,  27.55102041,
        28.57142857,  29.59183673]), array([  2.        , 

In [15]:
## Vectorize:
print(vertstk)
print(vertstk / 2)

[[   8.           24.           67.           87.           79.        ]
 [  48.           10.           94.           52.           98.        ]
 [  53.           66.           98.           14.           34.        ]
 [  24.           15.           60.           58.           16.        ]
 [   9.           93.           86.            2.           27.        ]
 [   4.           31.            1.           13.           83.        ]
 [   4.           91.           59.           67.            7.        ]
 [  49.           47.           65.           61.           14.        ]
 [  55.           71.           80.            2.           94.        ]
 [  19.           98.           63.           53.           27.        ]
 [   0.            2.04081633    4.08163265    6.12244898    8.16326531]
 [  10.20408163   12.24489796   14.28571429   16.32653061   18.36734694]
 [  20.40816327   22.44897959   24.48979592   26.53061224   28.57142857]
 [  30.6122449    32.65306122   34.69387755   36.73

In [16]:
# b. Here are two methods to cap your data at "25"
arr = vertstk/2
arr[arr > 25] = 25
print(arr)

# Alternatively, A quick "google" can help you find the 'clip' function, which caps maximum values.
print((vertstk / 2).clip(0, 25))


[[  4.          12.          25.          25.          25.        ]
 [ 24.           5.          25.          25.          25.        ]
 [ 25.          25.          25.           7.          17.        ]
 [ 12.           7.5         25.          25.           8.        ]
 [  4.5         25.          25.           1.          13.5       ]
 [  2.          15.5          0.5          6.5         25.        ]
 [  2.          25.          25.          25.           3.5       ]
 [ 24.5         23.5         25.          25.           7.        ]
 [ 25.          25.          25.           1.          25.        ]
 [  9.5         25.          25.          25.          13.5       ]
 [  0.           1.02040816   2.04081633   3.06122449   4.08163265]
 [  5.10204082   6.12244898   7.14285714   8.16326531   9.18367347]
 [ 10.20408163  11.2244898   12.24489796  13.26530612  14.28571429]
 [ 15.30612245  16.32653061  17.34693878  18.36734694  19.3877551 ]
 [ 20.40816327  21.42857143  22.44897959  23.469

In [17]:
#8. get column and row means for hozstk and vertstk
print(vertstk.shape)
print("Col Means")
print(np.mean(vertstk, axis=0))
print("Row Means")
print(np.mean(vertstk, axis=1))
print(type(np.mean(vertstk, axis=1)))

(20, 5)
Col Means
[ 36.60918367  51.27959184  58.65        46.47040816  50.99081633]
Row Means
[ 53.          60.4         53.          34.6         43.4         26.4
  45.6         47.2         60.4         52.           4.08163265
  14.28571429  24.48979592  34.69387755  44.89795918  55.10204082
  65.30612245  75.51020408  85.71428571  95.91836735]
<class 'numpy.ndarray'>


In [24]:
print("Col Means")
print(np.mean(hozstk, axis=0))
print("Row Means")
print(np.mean(hozstk, axis=1))

Col Means
[ 27.3         54.6         67.3         40.9         47.9         45.91836735
  47.95918367  50.          52.04081633  54.08163265]
Row Means
[ 28.54081633  37.34285714  38.74489796  34.64693878  44.14897959
  40.75102041  55.45306122  61.35510204  73.05714286  73.95918367]


In [23]:
hozstk.shape

(10, 10)